/* Shared project data — used by projects.html and project-detail.html */
const PROJECTS = [
  {
    id: 'gac-motor',
    title: 'GAC Motor Campaign',
    client: 'GAC Motor × Al Jamea',
    category: 'key',
    categoryLabel: 'Key Visual',
    year: '2024',
    tools: ['Adobe Photoshop', 'Midjourney', 'Adobe Illustrator'],
    description: 'Full key visual campaign for GAC Motor EMKOO GL 2024. Hero banners communicating a 50% down payment offer targeted at the Saudi Arabian automotive market — strong brand alignment across print and digital.',
    challenge: 'Communicate a complex financing offer clearly while keeping the visual language premium and automotive. The campaign needed to work across Arabic and English and across billboard, social, and digital ad formats.',
    solution: 'Led with a dramatic product shot composited against a cinematic background. Arabic calligraphy was integrated into the offer hierarchy. Color palette anchored to GAC brand guidelines while adding visual punch for social feeds.',
    solutions: ['Hero key visual for print & digital', 'Arabic typography layout', 'Product compositing & retouching', 'Campaign adaptation across formats'],
    cover: './projects/gac-motor/cover.jpg',
    gallery: ['./projects/gac-motor/01.jpg', './projects/gac-motor/02.jpg', './projects/gac-motor/03.jpg'],
    coverGrad: 'linear-gradient(135deg, #1c1200 0%, #2d1e00 50%, #3d2a00 100%)',
    next: 'rcmc-makkah',
    featured: true
  },
  {
    id: 'rcmc-makkah',
    title: 'RCMC — Makkah Campaign',
    client: 'Royal Commission for Makkah City',
    category: 'key',
    categoryLabel: 'Key Visual',
    year: '2024',
    tools: ['Adobe Photoshop', 'Adobe Illustrator'],
    description: 'Government campaign key visual for the Royal Commission for Makkah City and Holy Sites. Designed to convey heritage, civilization, and family connection to the holy city.',
    challenge: 'Translate a government brief about urban development and heritage into a warm, human visual that still carries institutional authority. Bilingual layout required balanced visual weight.',
    solution: 'Architecture and people composited at golden hour. Hierarchical typography balances Arabic prominence with English legibility. Warm tone anchors an otherwise technical subject.',
    solutions: ['Campaign concept & art direction', 'People & architecture compositing', 'Bilingual layout (Arabic/English)', 'Multi-format adaptation'],
    cover: './projects/rcmc-makkah/cover.jpg',
    gallery: ['./projects/rcmc-makkah/01.jpg', './projects/rcmc-makkah/02.jpg'],
    coverGrad: 'linear-gradient(135deg, #1a0f00 0%, #2d1a00 50%, #3d2500 100%)',
    next: 'abaza-auto',
    featured: false
  },
  {
    id: 'abaza-auto',
    title: 'ABAZA Auto Trading',
    client: 'ABAZA Auto Trading',
    category: 'social',
    categoryLabel: 'Social Media',
    year: '2024',
    tools: ['Adobe Photoshop', 'Adobe Illustrator'],
    description: 'Social media ad series for ABAZA Auto Trading promoting MG RX5, XPeng, and golf carts. Bold automotive visuals with financing offer highlights designed for Egyptian market.',
    challenge: 'Three different vehicles, three different audiences — all in one cohesive series. Each post needed to stand alone while feeling like part of a family.',
    solution: 'Unified by a dark cinematic color treatment and consistent offer-badge system. Each vehicle shot was individually composited and color-graded to match its personality.',
    solutions: ['3-post social series design', 'Car compositing & retouching', 'Offer typography hierarchy', 'Brand consistency across posts'],
    cover: './projects/abaza-auto/cover.jpg',
    gallery: ['./projects/abaza-auto/01.jpg', './projects/abaza-auto/02.jpg', './projects/abaza-auto/03.jpg'],
    coverGrad: 'linear-gradient(135deg, #001a14 0%, #002d22 50%, #003d30 100%)',
    next: 'flamingo-pets',
    featured: false
  },
  {
    id: 'flamingo-pets',
    title: 'Flamingo Pets — Pink Friday',
    client: 'Flamingo Pets Clinic',
    category: 'social',
    categoryLabel: 'Social Media',
    year: '2023',
    tools: ['Adobe Photoshop', 'Midjourney', 'KlingAI'],
    description: 'Pink Friday campaign for Flamingo Pets Clinic. AI-generated surreal visuals of cats and flamingos in a cohesive pink color world, designed to stop the scroll and drive clinic awareness.',
    challenge: 'Pet clinic social content is usually generic. The brief called for something surreal and share-worthy that would break through the noise during the Pink Friday retail moment.',
    solution: 'Built a full AI-generated world: cats in pink flamingo environments, flamingos in veterinary settings. Midjourney for stills, KlingAI for motion. Color palette locked to deep rose and magenta throughout.',
    solutions: ['AI image generation & art direction', 'Brand-aligned color world creation', '3-post campaign series', 'Surreal product compositing'],
    cover: './projects/flamingo-pets/cover.jpg',
    gallery: ['./projects/flamingo-pets/01.jpg', './projects/flamingo-pets/02.jpg', './projects/flamingo-pets/03.jpg'],
    coverGrad: 'linear-gradient(135deg, #1a0014 0%, #2d0022 50%, #3d0030 100%)',
    next: 'rcmc-infographic',
    featured: false
  },
  {
    id: 'rcmc-infographic',
    title: 'RCMC — Infographic Series',
    client: 'Royal Commission for Makkah City',
    category: 'info',
    categoryLabel: 'Infographic',
    year: '2024',
    tools: ['Adobe Illustrator', 'Adobe InDesign', 'Adobe Photoshop'],
    description: 'Data infographic series communicating urban development progress in Makkah neighborhoods. Clean, authoritative government visual style with Arabic typography and structured data hierarchy.',
    challenge: 'Dense statistical data about infrastructure projects needed to become accessible and visually compelling for public communication, while meeting strict government brand guidelines.',
    solution: 'Structured each infographic around a single data story. Visual hierarchy built with icon systems, progress indicators, and typographic scale. Arabic numeral formatting throughout.',
    solutions: ['Data visualization design', 'Arabic infographic layout', 'Government brand compliance', 'Multi-format infographic series'],
    cover: './projects/rcmc-infographic/cover.jpg',
    gallery: ['./projects/rcmc-infographic/01.jpg', './projects/rcmc-infographic/02.jpg'],
    coverGrad: 'linear-gradient(135deg, #00102a 0%, #001840 50%, #001f50 100%)',
    next: 'film-posters',
    featured: false
  },
  {
    id: 'film-posters',
    title: 'Creative Film Poster Series',
    client: 'Personal / Creative Work',
    category: 'film',
    categoryLabel: 'Film Poster',
    year: '2023–2024',
    tools: ['Adobe Photoshop', 'Midjourney', 'Adobe Illustrator'],
    description: 'Personal creative series reimagining iconic films and shows — The Matrix 4, Blacklist, Squid Game, TikTok Banned — through original poster design. Pure creative expression with no client brief.',
    challenge: 'Iconic IPs have entrenched visual identities. The creative challenge was to produce interpretations that feel fresh and personal while being instantly recognizable.',
    solution: 'Each poster built around one unexpected visual decision — an inverted color palette, a different character POV, an unconventional crop. AI used to generate raw material, Photoshop for final craft.',
    solutions: ['Original poster concept & design', 'Photo manipulation & compositing', 'Custom typography treatment', 'Cinematic color grading'],
    cover: './projects/film-posters/cover.jpg',
    gallery: ['./projects/film-posters/01.jpg', './projects/film-posters/02.jpg', './projects/film-posters/03.jpg', './projects/film-posters/04.jpg'],
    coverGrad: 'linear-gradient(135deg, #1a0000 0%, #2d0808 50%, #3d0f0f 100%)',
    next: 'gac-motor',
    featured: false
  }
];
